version: '3'

services:

  mysql:
    image: 'mysql:latest'
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_DATABASE=broker
    ports:
      - '3306:3306'
    volumes:
      - './database/mysql/items.sql:/docker-entrypoint-initdb.d/items.sql'

  #swagger-ui:
  #  image: swaggerapi/swagger-ui
  #  container_name: swagger_ui_container
  #  ports:
  #      - "8080:8081"
  #  volumes:
  #    - ../api/broker/swagger.json:/swagger.json
  #  environment:
  #    SWAGGER_JSON: /swagger.json
