// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.19.6
// source: api/exchange/exchange.proto

package exchange

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type OHLCV struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ID       int64   `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"` // внутренний идентификатор, просто авто-инкремент
	Time     int32   `protobuf:"varint,2,opt,name=Time,proto3" json:"Time,omitempty"`
	Interval int32   `protobuf:"varint,3,opt,name=Interval,proto3" json:"Interval,omitempty"` // в данном случае - 1 секунда
	Open     float32 `protobuf:"fixed32,4,opt,name=Open,proto3" json:"Open,omitempty"`
	High     float32 `protobuf:"fixed32,5,opt,name=High,proto3" json:"High,omitempty"`
	Low      float32 `protobuf:"fixed32,6,opt,name=Low,proto3" json:"Low,omitempty"`
	Close    float32 `protobuf:"fixed32,7,opt,name=Close,proto3" json:"Close,omitempty"`
	Volume   int32   `protobuf:"varint,8,opt,name=Volume,proto3" json:"Volume,omitempty"`
	Ticker   string  `protobuf:"bytes,9,opt,name=Ticker,proto3" json:"Ticker,omitempty"`
}

func (x *OHLCV) Reset() {
	*x = OHLCV{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_exchange_exchange_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OHLCV) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OHLCV) ProtoMessage() {}

func (x *OHLCV) ProtoReflect() protoreflect.Message {
	mi := &file_api_exchange_exchange_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OHLCV.ProtoReflect.Descriptor instead.
func (*OHLCV) Descriptor() ([]byte, []int) {
	return file_api_exchange_exchange_proto_rawDescGZIP(), []int{0}
}

func (x *OHLCV) GetID() int64 {
	if x != nil {
		return x.ID
	}
	return 0
}

func (x *OHLCV) GetTime() int32 {
	if x != nil {
		return x.Time
	}
	return 0
}

func (x *OHLCV) GetInterval() int32 {
	if x != nil {
		return x.Interval
	}
	return 0
}

func (x *OHLCV) GetOpen() float32 {
	if x != nil {
		return x.Open
	}
	return 0
}

func (x *OHLCV) GetHigh() float32 {
	if x != nil {
		return x.High
	}
	return 0
}

func (x *OHLCV) GetLow() float32 {
	if x != nil {
		return x.Low
	}
	return 0
}

func (x *OHLCV) GetClose() float32 {
	if x != nil {
		return x.Close
	}
	return 0
}

func (x *OHLCV) GetVolume() int32 {
	if x != nil {
		return x.Volume
	}
	return 0
}

func (x *OHLCV) GetTicker() string {
	if x != nil {
		return x.Ticker
	}
	return ""
}

type Deal struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ID       int64   `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"` // DealID который вернулся вам при простановке заявки
	BrokerID int32   `protobuf:"varint,2,opt,name=BrokerID,proto3" json:"BrokerID,omitempty"`
	ClientID int32   `protobuf:"varint,3,opt,name=ClientID,proto3" json:"ClientID,omitempty"`
	Ticker   string  `protobuf:"bytes,4,opt,name=Ticker,proto3" json:"Ticker,omitempty"`
	Volume   int32   `protobuf:"varint,5,opt,name=Volume,proto3" json:"Volume,omitempty"`   // сколько купили-продали
	Partial  bool    `protobuf:"varint,6,opt,name=Partial,proto3" json:"Partial,omitempty"` // флаг что сделка клиента исполнилсь частично
	Time     int32   `protobuf:"varint,7,opt,name=Time,proto3" json:"Time,omitempty"`
	Price    float32 `protobuf:"fixed32,8,opt,name=Price,proto3" json:"Price,omitempty"`
}

func (x *Deal) Reset() {
	*x = Deal{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_exchange_exchange_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Deal) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Deal) ProtoMessage() {}

func (x *Deal) ProtoReflect() protoreflect.Message {
	mi := &file_api_exchange_exchange_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Deal.ProtoReflect.Descriptor instead.
func (*Deal) Descriptor() ([]byte, []int) {
	return file_api_exchange_exchange_proto_rawDescGZIP(), []int{1}
}

func (x *Deal) GetID() int64 {
	if x != nil {
		return x.ID
	}
	return 0
}

func (x *Deal) GetBrokerID() int32 {
	if x != nil {
		return x.BrokerID
	}
	return 0
}

func (x *Deal) GetClientID() int32 {
	if x != nil {
		return x.ClientID
	}
	return 0
}

func (x *Deal) GetTicker() string {
	if x != nil {
		return x.Ticker
	}
	return ""
}

func (x *Deal) GetVolume() int32 {
	if x != nil {
		return x.Volume
	}
	return 0
}

func (x *Deal) GetPartial() bool {
	if x != nil {
		return x.Partial
	}
	return false
}

func (x *Deal) GetTime() int32 {
	if x != nil {
		return x.Time
	}
	return 0
}

func (x *Deal) GetPrice() float32 {
	if x != nil {
		return x.Price
	}
	return 0
}

type DealID struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ID       int64 `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	BrokerID int64 `protobuf:"varint,2,opt,name=BrokerID,proto3" json:"BrokerID,omitempty"`
}

func (x *DealID) Reset() {
	*x = DealID{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_exchange_exchange_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DealID) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DealID) ProtoMessage() {}

func (x *DealID) ProtoReflect() protoreflect.Message {
	mi := &file_api_exchange_exchange_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DealID.ProtoReflect.Descriptor instead.
func (*DealID) Descriptor() ([]byte, []int) {
	return file_api_exchange_exchange_proto_rawDescGZIP(), []int{2}
}

func (x *DealID) GetID() int64 {
	if x != nil {
		return x.ID
	}
	return 0
}

func (x *DealID) GetBrokerID() int64 {
	if x != nil {
		return x.BrokerID
	}
	return 0
}

type BrokerID struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ID int64 `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
}

func (x *BrokerID) Reset() {
	*x = BrokerID{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_exchange_exchange_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BrokerID) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BrokerID) ProtoMessage() {}

func (x *BrokerID) ProtoReflect() protoreflect.Message {
	mi := &file_api_exchange_exchange_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BrokerID.ProtoReflect.Descriptor instead.
func (*BrokerID) Descriptor() ([]byte, []int) {
	return file_api_exchange_exchange_proto_rawDescGZIP(), []int{3}
}

func (x *BrokerID) GetID() int64 {
	if x != nil {
		return x.ID
	}
	return 0
}

type CancelResult struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Success bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
}

func (x *CancelResult) Reset() {
	*x = CancelResult{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_exchange_exchange_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CancelResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelResult) ProtoMessage() {}

func (x *CancelResult) ProtoReflect() protoreflect.Message {
	mi := &file_api_exchange_exchange_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelResult.ProtoReflect.Descriptor instead.
func (*CancelResult) Descriptor() ([]byte, []int) {
	return file_api_exchange_exchange_proto_rawDescGZIP(), []int{4}
}

func (x *CancelResult) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

var File_api_exchange_exchange_proto protoreflect.FileDescriptor

var file_api_exchange_exchange_proto_rawDesc = []byte{
	0x0a, 0x1b, 0x61, 0x70, 0x69, 0x2f, 0x65, 0x78, 0x63, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x2f, 0x65,
	0x78, 0x63, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x04, 0x6d,
	0x61, 0x69, 0x6e, 0x22, 0xc7, 0x01, 0x0a, 0x05, 0x4f, 0x48, 0x4c, 0x43, 0x56, 0x12, 0x0e, 0x0a,
	0x02, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x49, 0x44, 0x12, 0x12, 0x0a,
	0x04, 0x54, 0x69, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x54, 0x69, 0x6d,
	0x65, 0x12, 0x1a, 0x0a, 0x08, 0x49, 0x6e, 0x74, 0x65, 0x72, 0x76, 0x61, 0x6c, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x08, 0x49, 0x6e, 0x74, 0x65, 0x72, 0x76, 0x61, 0x6c, 0x12, 0x12, 0x0a,
	0x04, 0x4f, 0x70, 0x65, 0x6e, 0x18, 0x04, 0x20, 0x01, 0x28, 0x02, 0x52, 0x04, 0x4f, 0x70, 0x65,
	0x6e, 0x12, 0x12, 0x0a, 0x04, 0x48, 0x69, 0x67, 0x68, 0x18, 0x05, 0x20, 0x01, 0x28, 0x02, 0x52,
	0x04, 0x48, 0x69, 0x67, 0x68, 0x12, 0x10, 0x0a, 0x03, 0x4c, 0x6f, 0x77, 0x18, 0x06, 0x20, 0x01,
	0x28, 0x02, 0x52, 0x03, 0x4c, 0x6f, 0x77, 0x12, 0x14, 0x0a, 0x05, 0x43, 0x6c, 0x6f, 0x73, 0x65,
	0x18, 0x07, 0x20, 0x01, 0x28, 0x02, 0x52, 0x05, 0x43, 0x6c, 0x6f, 0x73, 0x65, 0x12, 0x16, 0x0a,
	0x06, 0x56, 0x6f, 0x6c, 0x75, 0x6d, 0x65, 0x18, 0x08, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x56,
	0x6f, 0x6c, 0x75, 0x6d, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x54, 0x69, 0x63, 0x6b, 0x65, 0x72, 0x18,
	0x09, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x54, 0x69, 0x63, 0x6b, 0x65, 0x72, 0x22, 0xc2, 0x01,
	0x0a, 0x04, 0x44, 0x65, 0x61, 0x6c, 0x12, 0x0e, 0x0a, 0x02, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x02, 0x49, 0x44, 0x12, 0x1a, 0x0a, 0x08, 0x42, 0x72, 0x6f, 0x6b, 0x65, 0x72,
	0x49, 0x44, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x42, 0x72, 0x6f, 0x6b, 0x65, 0x72,
	0x49, 0x44, 0x12, 0x1a, 0x0a, 0x08, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x49, 0x44, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x49, 0x44, 0x12, 0x16,
	0x0a, 0x06, 0x54, 0x69, 0x63, 0x6b, 0x65, 0x72, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06,
	0x54, 0x69, 0x63, 0x6b, 0x65, 0x72, 0x12, 0x16, 0x0a, 0x06, 0x56, 0x6f, 0x6c, 0x75, 0x6d, 0x65,
	0x18, 0x05, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x56, 0x6f, 0x6c, 0x75, 0x6d, 0x65, 0x12, 0x18,
	0x0a, 0x07, 0x50, 0x61, 0x72, 0x74, 0x69, 0x61, 0x6c, 0x18, 0x06, 0x20, 0x01, 0x28, 0x08, 0x52,
	0x07, 0x50, 0x61, 0x72, 0x74, 0x69, 0x61, 0x6c, 0x12, 0x12, 0x0a, 0x04, 0x54, 0x69, 0x6d, 0x65,
	0x18, 0x07, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x14, 0x0a, 0x05,
	0x50, 0x72, 0x69, 0x63, 0x65, 0x18, 0x08, 0x20, 0x01, 0x28, 0x02, 0x52, 0x05, 0x50, 0x72, 0x69,
	0x63, 0x65, 0x22, 0x34, 0x0a, 0x06, 0x44, 0x65, 0x61, 0x6c, 0x49, 0x44, 0x12, 0x0e, 0x0a, 0x02,
	0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x49, 0x44, 0x12, 0x1a, 0x0a, 0x08,
	0x42, 0x72, 0x6f, 0x6b, 0x65, 0x72, 0x49, 0x44, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08,
	0x42, 0x72, 0x6f, 0x6b, 0x65, 0x72, 0x49, 0x44, 0x22, 0x1a, 0x0a, 0x08, 0x42, 0x72, 0x6f, 0x6b,
	0x65, 0x72, 0x49, 0x44, 0x12, 0x0e, 0x0a, 0x02, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x02, 0x49, 0x44, 0x22, 0x28, 0x0a, 0x0c, 0x43, 0x61, 0x6e, 0x63, 0x65, 0x6c, 0x52, 0x65,
	0x73, 0x75, 0x6c, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x32, 0xb7,
	0x01, 0x0a, 0x08, 0x45, 0x78, 0x63, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x12, 0x2c, 0x0a, 0x09, 0x53,
	0x74, 0x61, 0x74, 0x69, 0x73, 0x74, 0x69, 0x63, 0x12, 0x0e, 0x2e, 0x6d, 0x61, 0x69, 0x6e, 0x2e,
	0x42, 0x72, 0x6f, 0x6b, 0x65, 0x72, 0x49, 0x44, 0x1a, 0x0b, 0x2e, 0x6d, 0x61, 0x69, 0x6e, 0x2e,
	0x4f, 0x48, 0x4c, 0x43, 0x56, 0x22, 0x00, 0x30, 0x01, 0x12, 0x24, 0x0a, 0x06, 0x43, 0x72, 0x65,
	0x61, 0x74, 0x65, 0x12, 0x0a, 0x2e, 0x6d, 0x61, 0x69, 0x6e, 0x2e, 0x44, 0x65, 0x61, 0x6c, 0x1a,
	0x0c, 0x2e, 0x6d, 0x61, 0x69, 0x6e, 0x2e, 0x44, 0x65, 0x61, 0x6c, 0x49, 0x44, 0x22, 0x00, 0x12,
	0x2c, 0x0a, 0x06, 0x43, 0x61, 0x6e, 0x63, 0x65, 0x6c, 0x12, 0x0c, 0x2e, 0x6d, 0x61, 0x69, 0x6e,
	0x2e, 0x44, 0x65, 0x61, 0x6c, 0x49, 0x44, 0x1a, 0x12, 0x2e, 0x6d, 0x61, 0x69, 0x6e, 0x2e, 0x43,
	0x61, 0x6e, 0x63, 0x65, 0x6c, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x22, 0x00, 0x12, 0x29, 0x0a,
	0x07, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x73, 0x12, 0x0e, 0x2e, 0x6d, 0x61, 0x69, 0x6e, 0x2e,
	0x42, 0x72, 0x6f, 0x6b, 0x65, 0x72, 0x49, 0x44, 0x1a, 0x0a, 0x2e, 0x6d, 0x61, 0x69, 0x6e, 0x2e,
	0x44, 0x65, 0x61, 0x6c, 0x22, 0x00, 0x30, 0x01, 0x42, 0x10, 0x5a, 0x0e, 0x2e, 0x2f, 0x61, 0x70,
	0x69, 0x2f, 0x65, 0x78, 0x63, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_api_exchange_exchange_proto_rawDescOnce sync.Once
	file_api_exchange_exchange_proto_rawDescData = file_api_exchange_exchange_proto_rawDesc
)

func file_api_exchange_exchange_proto_rawDescGZIP() []byte {
	file_api_exchange_exchange_proto_rawDescOnce.Do(func() {
		file_api_exchange_exchange_proto_rawDescData = protoimpl.X.CompressGZIP(file_api_exchange_exchange_proto_rawDescData)
	})
	return file_api_exchange_exchange_proto_rawDescData
}

var file_api_exchange_exchange_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_api_exchange_exchange_proto_goTypes = []interface{}{
	(*OHLCV)(nil),        // 0: main.OHLCV
	(*Deal)(nil),         // 1: main.Deal
	(*DealID)(nil),       // 2: main.DealID
	(*BrokerID)(nil),     // 3: main.BrokerID
	(*CancelResult)(nil), // 4: main.CancelResult
}
var file_api_exchange_exchange_proto_depIdxs = []int32{
	3, // 0: main.Exchange.Statistic:input_type -> main.BrokerID
	1, // 1: main.Exchange.Create:input_type -> main.Deal
	2, // 2: main.Exchange.Cancel:input_type -> main.DealID
	3, // 3: main.Exchange.Results:input_type -> main.BrokerID
	0, // 4: main.Exchange.Statistic:output_type -> main.OHLCV
	2, // 5: main.Exchange.Create:output_type -> main.DealID
	4, // 6: main.Exchange.Cancel:output_type -> main.CancelResult
	1, // 7: main.Exchange.Results:output_type -> main.Deal
	4, // [4:8] is the sub-list for method output_type
	0, // [0:4] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_exchange_exchange_proto_init() }
func file_api_exchange_exchange_proto_init() {
	if File_api_exchange_exchange_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_api_exchange_exchange_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OHLCV); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_exchange_exchange_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Deal); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_exchange_exchange_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DealID); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_exchange_exchange_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BrokerID); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_exchange_exchange_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CancelResult); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_api_exchange_exchange_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_exchange_exchange_proto_goTypes,
		DependencyIndexes: file_api_exchange_exchange_proto_depIdxs,
		MessageInfos:      file_api_exchange_exchange_proto_msgTypes,
	}.Build()
	File_api_exchange_exchange_proto = out.File
	file_api_exchange_exchange_proto_rawDesc = nil
	file_api_exchange_exchange_proto_goTypes = nil
	file_api_exchange_exchange_proto_depIdxs = nil
}
